---
- name: "PLAY 1: Infrastructure-as-code using NETCONF"
  hosts: all
  connection: netconf
  tasks:
    - name: "TASK 1: Update Loopback interface with NETCONF"
      netconf_config:
        content: |
           <config>
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                 <interface>
                    <Loopback operation="replace">
                       <name>1</name>
                       <description>Interface configured via NETCONF</description>
                       <ip>
                         <address>
                            <primary>
                               <address>10.10.10.10</address>
                               <mask>255.255.255.255</mask>
                            </primary>
                         </address>
                       </ip>
                    </Loopback>
                 </interface>
              </native>
           </config>
...
